# author : snehashish laskar
# date : 20-08-2021
# time : 19:38

# THIS IS A PASSWORD MANAGER TO STORE AND MANAGE PASSWORDS
# IT USES SQLITE DATABSE FOR STORING PASSWORDS WHICH CAN BE 
# STORED IN THE FORMS OF FILES LOCALLY ANYWHERE. 
# IT HAS A BASIC CLI MENU FOR USAGE

# Imports
from db import *
from functions import *